-- ============================================================================
-- Kerja-AI — COMPLETE database setup (single file).
-- AI/ML & data jobs for Malaysia & Singapore.
--
-- HOW TO APPLY (pick one):
--   A) Supabase Dashboard → SQL Editor → paste this whole file → Run.
--   B) CLI:  supabase link --project-ref <your-ref>  &&  supabase db push
--      (this file is also split as migrations under supabase/migrations/)
--
-- Safe to re-run: every object uses IF NOT EXISTS / DROP ... IF EXISTS.
-- Roles anon / authenticated / service_role already exist in every Supabase
-- project. RLS is ON for every table; the apps write via the service_role key
-- (which bypasses RLS), anon can only read published content + submit a
-- pending job + log analytics events.
-- ============================================================================

-- ── Extensions & shared trigger functions ──────────────────────────────────
create extension if not exists "pgcrypto";
create extension if not exists "uuid-ossp";

create or replace function public.update_updated_at_column()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Auto-set job expiry on insert (30 days, 60 if featured).
create or replace function public.set_job_expiry()
returns trigger language plpgsql as $$
begin
  new.expires_at := case
    when new.is_featured = true then now() + interval '60 days'
    else now() + interval '30 days'
  end;
  return new;
end;
$$;

-- ── companies ──────────────────────────────────────────────────────────────
create table if not exists public.companies (
  id             uuid primary key default gen_random_uuid(),
  name           text not null,
  slug           text not null unique,
  logo_url       text,
  website        text,
  linkedin       text,
  twitter        text,
  facebook       text,
  tagline        text,
  contact_email  text,
  description    text,
  industry       text,
  company_size   text,
  hq_location    text,
  remote_policy  text,
  year_founded   text,
  careers_url    text,
  glassdoor_url  text,
  created_at     timestamptz default timezone('utc', now()),
  updated_at     timestamptz default now()
);
drop trigger if exists set_updated_at on public.companies;
create trigger set_updated_at before update on public.companies
  for each row execute function public.update_updated_at_column();

-- ── authors (blog) ─────────────────────────────────────────────────────────
create table if not exists public.authors (
  id          bigint generated by default as identity primary key,
  name        text not null,
  slug        text not null unique,
  title       text,
  bio         text,
  avatar_url  text,
  linkedin    text,
  twitter     text,
  website     text,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

-- ── categories (blog categories — the only taxonomy stored in the DB) ───────
create table if not exists public.categories (
  id          uuid primary key default uuid_generate_v4(),
  name        text not null unique,
  created_at  timestamptz default timezone('utc', now())
);

-- ── blogs ──────────────────────────────────────────────────────────────────
create table if not exists public.blogs (
  id                  bigint generated by default as identity primary key,
  title               text not null,
  slug                text not null unique,
  content             text not null,
  excerpt             text,
  category            text not null,
  date                date not null,
  status              text not null default 'draft' check (status in ('draft','published')),
  author              text,
  author_id           bigint references public.authors(id) on delete set null,
  featured_image      text,
  featured_image_alt  text,
  seo_title           text,
  seo_description     text,
  meta_description    text,
  canonical_url       text,
  og_image            text,
  schema_type         text,
  last_saved_at       timestamp without time zone,
  created_at          timestamptz not null default now(),
  updated_at          timestamp without time zone default now()
);
create index if not exists idx_blogs_status on public.blogs (status);
drop trigger if exists set_updated_at on public.blogs;
create trigger set_updated_at before update on public.blogs
  for each row execute function public.update_updated_at_column();

-- ── jobs  (schema identical to Kerja-Remote; remote_type adds 'Onsite') ─────
create table if not exists public.jobs (
  id                   uuid primary key default gen_random_uuid(),
  slug                 text not null unique,
  title                text not null,
  description          text not null,
  job_type             text[] not null,
  job_category         text[] not null,
  job_location         text[] not null,
  min_salary           numeric,
  max_salary           numeric,
  currency             text not null default 'MYR',
  apply_url            text not null,
  tags                 text[],
  is_featured          boolean default false,
  is_active            boolean default true,
  company_id           uuid references public.companies(id) on delete set null,
  status               text default 'pending',
  remote_type          text not null default '100% Remote'
                         check (remote_type in ('100% Remote','Hybrid','Onsite')),
  billing_plan         text not null default 'free' check (billing_plan in ('free','paid')),
  visibility_plan      text not null default 'public'
                         check (visibility_plan in ('public','private_early_access')),
  seo_title            text,
  seo_description      text,
  goes_public_at       timestamptz default (now() + interval '12 hours'),
  expires_at           date,
  valid_through        date,
  stripe_session_id    text,
  featured_addon_paid  boolean not null default false,
  paid_amount_total    integer,
  paid_currency        text,
  paid_at              timestamptz,
  created_at           timestamptz default timezone('utc', now()),
  updated_at           timestamp without time zone default now()
);
create index if not exists idx_jobs_status  on public.jobs (status);
create index if not exists idx_jobs_company on public.jobs (company_id);
drop trigger if exists set_updated_at on public.jobs;
create trigger set_updated_at before update on public.jobs
  for each row execute function public.update_updated_at_column();
drop trigger if exists trigger_set_job_expiry on public.jobs;
create trigger trigger_set_job_expiry before insert on public.jobs
  for each row execute function public.set_job_expiry();

-- ── job_payments (kept for jobs_with_payment view / future paid tier) ───────
create table if not exists public.job_payments (
  id                 uuid primary key default gen_random_uuid(),
  job_id             uuid references public.jobs(id) on delete cascade,
  stripe_session_id  text not null,
  payment_status     text not null default 'paid'
                       check (payment_status in ('paid','unpaid','refunded','disputed','cancelled')),
  amount             integer not null check (amount >= 0),
  currency           text not null check (char_length(currency) = 3),
  country            text,
  email              text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

-- ── job_events (analytics: view/click stream) ──────────────────────────────
create table if not exists public.job_events (
  id          uuid primary key default gen_random_uuid(),
  job_id      uuid references public.jobs(id) on delete cascade,
  event_type  text check (event_type in ('view','click')),
  created_at  timestamptz default now()
);
create index if not exists idx_job_events_type_job on public.job_events (event_type, job_id);

-- ── newsletter_subscribers ─────────────────────────────────────────────────
create table if not exists public.newsletter_subscribers (
  id             uuid primary key default gen_random_uuid(),
  email          text not null unique,
  name           text,
  country        text,
  source         text default 'website',
  subscribed_at  timestamptz default now()
);

-- ── job_ingestion (scraper/AI extraction staging table) ────────────────────
create table if not exists public.job_ingestion (
  id            uuid primary key default gen_random_uuid(),
  source_url    text not null unique,
  source_name   text,
  country       text check (country in ('MY','SG')),
  city          text,
  raw_title     text,
  raw_company   text,
  raw_location  text,
  extracted     jsonb,
  status        text not null default 'pending'
                  check (status in ('pending','imported','rejected','duplicate','error')),
  job_id        uuid references public.jobs(id) on delete set null,
  error         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists idx_job_ingestion_status on public.job_ingestion (status);
drop trigger if exists set_updated_at on public.job_ingestion;
create trigger set_updated_at before update on public.job_ingestion
  for each row execute function public.update_updated_at_column();

-- ── Views ──────────────────────────────────────────────────────────────────
create or replace view public.companies_with_job_count as
  select c.id, c.name, c.slug, c.logo_url, count(j.id) as job_count
  from public.companies c
  left join public.jobs j on j.company_id = c.id and j.status = 'published'
  group by c.id;

create or replace view public.sorted_companies as
  select id, name, lower(name) as name_lower, slug, website, tagline, logo_url, created_at
  from public.companies;

create or replace view public.jobs_with_payment as
  select j.id, j.title, j.slug, j.description, j.apply_url, j.company_id,
         j.job_type, j.job_category, j.job_location, j.min_salary, j.max_salary,
         j.currency, j.tags, j.status, j.is_featured, j.is_active, j.billing_plan,
         j.visibility_plan, j.seo_title, j.seo_description, j.goes_public_at,
         j.expires_at, j.valid_through, j.created_at, j.updated_at,
         p.email as paid_email, p.amount as paid_amount, p.currency as paid_currency,
         p.country as paid_country, p.payment_status as paid_payment_status,
         p.stripe_session_id, p.created_at as paid_created_at
  from public.jobs j
  left join public.job_payments p on p.job_id = j.id;

-- ── Analytics / maintenance functions ──────────────────────────────────────
create or replace function public.archive_expired_jobs()
returns void language plpgsql as $$
begin
  update public.jobs set status = 'archived'
    where expires_at < now() and status = 'published';
  delete from public.jobs
    where status = 'archived' and expires_at < now() - interval '7 days';
end;
$$;

create or replace function public.get_job_stats(p_job_id uuid)
returns table(views bigint, clicks bigint) language sql stable as $$
  select count(*) filter (where event_type = 'view'),
         count(*) filter (where event_type = 'click')
  from public.job_events where job_id = p_job_id;
$$;

create or replace function public.get_jobs_stats(p_job_ids uuid[])
returns table(job_id uuid, views bigint, clicks bigint)
language sql stable security definer set search_path = public, pg_temp as $$
  select job_id,
         count(*) filter (where event_type = 'view'),
         count(*) filter (where event_type = 'click')
  from public.job_events where job_id = any(p_job_ids) group by job_id;
$$;

create or replace function public.job_events_daily(p_start timestamptz, p_end timestamptz)
returns table(day date, views bigint, clicks bigint)
language sql stable security definer set search_path = public, pg_temp as $$
  select d.day::date,
    coalesce(sum(case when je.event_type = 'view'  then 1 else 0 end), 0)::bigint,
    coalesce(sum(case when je.event_type = 'click' then 1 else 0 end), 0)::bigint
  from generate_series(p_start::date, (p_end - interval '1 microsecond')::date, interval '1 day') as d(day)
  left join public.job_events je
    on je.created_at >= greatest(d.day::timestamptz, p_start)
   and je.created_at <  least((d.day + interval '1 day')::timestamptz, p_end)
   and je.event_type in ('view','click')
  group by d.day order by d.day;
$$;

create or replace function public.top_jobs_by_event(p_event_type text, p_limit integer default 5)
returns table(job_id uuid, event_count bigint)
language sql stable security definer set search_path = public, pg_temp as $$
  select je.job_id, count(*) from public.job_events je
  where je.event_type = p_event_type and je.job_id is not null
  group by je.job_id order by count(*) desc limit p_limit;
$$;

create or replace function public.top_jobs_by_event_windowed(
  p_event_type text, p_start timestamptz, p_end timestamptz, p_limit integer default 6)
returns table(job_id uuid, event_count bigint)
language sql stable security definer set search_path = public, pg_temp as $$
  select je.job_id, count(*) from public.job_events je
  where je.event_type = p_event_type and je.job_id is not null
    and je.created_at >= p_start and je.created_at < p_end
  group by je.job_id order by count(*) desc limit p_limit;
$$;

create or replace function public.monthly_published_jobs()
returns table(year integer, month integer, total integer) language sql as $$
  select extract(year from created_at)::int, extract(month from created_at)::int, count(*)::int
  from public.jobs where status = 'published' group by 1,2 order by 1,2;
$$;

create or replace function public.monthly_registered_companies()
returns table(year integer, month integer, total integer) language sql as $$
  select extract(year from created_at)::int, extract(month from created_at)::int, count(*)::int
  from public.companies group by 1,2 order by 1,2;
$$;

create or replace function public.monthly_blog_posts()
returns table(year integer, month integer, total integer) language sql as $$
  select extract(year from created_at)::int, extract(month from created_at)::int, count(*)::int
  from public.blogs where status = 'published' group by 1,2 order by 1,2;
$$;

-- ============================================================================
-- Row Level Security
-- ============================================================================
alter table public.companies              enable row level security;
alter table public.authors                enable row level security;
alter table public.categories             enable row level security;
alter table public.blogs                  enable row level security;
alter table public.jobs                   enable row level security;
alter table public.job_payments           enable row level security;
alter table public.job_events             enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.job_ingestion          enable row level security;

-- Public (anon) reads of published/public content
drop policy if exists "anon read published jobs" on public.jobs;
create policy "anon read published jobs" on public.jobs
  for select to anon using (status = 'published' and goes_public_at <= now());

drop policy if exists "anon read published blogs" on public.blogs;
create policy "anon read published blogs" on public.blogs
  for select to anon using (status = 'published');

drop policy if exists "anon read companies" on public.companies;
create policy "anon read companies" on public.companies for select to anon using (true);

drop policy if exists "anon read authors" on public.authors;
create policy "anon read authors" on public.authors for select to anon using (true);

drop policy if exists "anon read categories" on public.categories;
create policy "anon read categories" on public.categories for select to anon using (true);

-- Public submission surfaces (moderation queue)
drop policy if exists "anon submit pending job" on public.jobs;
create policy "anon submit pending job" on public.jobs
  for insert to anon with check (status = 'pending' and billing_plan = 'free');

drop policy if exists "anon create company" on public.companies;
create policy "anon create company" on public.companies
  for insert to anon with check (true);

drop policy if exists "anon insert job events" on public.job_events;
create policy "anon insert job events" on public.job_events
  for insert to anon with check (true);

-- Authenticated (admin) full access
drop policy if exists "auth full jobs" on public.jobs;
create policy "auth full jobs" on public.jobs to authenticated using (true) with check (true);

drop policy if exists "auth full companies" on public.companies;
create policy "auth full companies" on public.companies to authenticated using (true) with check (true);

drop policy if exists "auth full blogs" on public.blogs;
create policy "auth full blogs" on public.blogs to authenticated using (true) with check (true);

drop policy if exists "auth full authors" on public.authors;
create policy "auth full authors" on public.authors to authenticated using (true) with check (true);

drop policy if exists "auth full categories" on public.categories;
create policy "auth full categories" on public.categories to authenticated using (true) with check (true);

drop policy if exists "auth read events" on public.job_events;
create policy "auth read events" on public.job_events for select to authenticated using (true);

drop policy if exists "auth full payments" on public.job_payments;
create policy "auth full payments" on public.job_payments to authenticated using (true) with check (true);

drop policy if exists "auth full subscribers" on public.newsletter_subscribers;
create policy "auth full subscribers" on public.newsletter_subscribers to authenticated using (true) with check (true);

drop policy if exists "auth full ingestion" on public.job_ingestion;
create policy "auth full ingestion" on public.job_ingestion to authenticated using (true) with check (true);

-- ── Grants (RLS still governs rows; no anon grants on PII/payments/ingestion) ─
grant usage on schema public to anon, authenticated, service_role;
grant select on public.jobs, public.blogs, public.companies, public.authors,
  public.categories, public.companies_with_job_count, public.sorted_companies,
  public.jobs_with_payment to anon;
grant insert on public.jobs, public.companies, public.job_events to anon;
grant all on public.jobs, public.companies, public.blogs, public.authors,
  public.categories, public.job_events, public.job_payments,
  public.newsletter_subscribers, public.job_ingestion to authenticated, service_role;
grant select on public.companies_with_job_count, public.sorted_companies,
  public.jobs_with_payment to authenticated, service_role;
grant execute on function public.get_jobs_stats(uuid[]),
  public.job_events_daily(timestamptz, timestamptz),
  public.top_jobs_by_event(text, integer),
  public.top_jobs_by_event_windowed(text, timestamptz, timestamptz, integer)
  to anon, authenticated, service_role;

-- ============================================================================
-- Storage buckets + policies
-- ============================================================================
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values
  ('company-logos',   'company-logos',   true, 2097152, array['image/png','image/jpeg','image/webp','image/svg+xml']),
  ('blog-images',     'blog-images',     true, 5242880, array['image/png','image/jpeg','image/webp','image/gif']),
  ('featured_images', 'featured_images', true, 5242880, array['image/png','image/jpeg','image/webp'])
on conflict (id) do nothing;

drop policy if exists "public read kerja-ai buckets" on storage.objects;
create policy "public read kerja-ai buckets" on storage.objects
  for select to anon, authenticated
  using (bucket_id in ('company-logos','blog-images','featured_images'));

drop policy if exists "auth write kerja-ai buckets" on storage.objects;
create policy "auth write kerja-ai buckets" on storage.objects
  for insert to authenticated
  with check (bucket_id in ('company-logos','blog-images','featured_images'));

drop policy if exists "auth update kerja-ai buckets" on storage.objects;
create policy "auth update kerja-ai buckets" on storage.objects
  for update to authenticated
  using (bucket_id in ('company-logos','blog-images','featured_images'));

drop policy if exists "auth delete kerja-ai buckets" on storage.objects;
create policy "auth delete kerja-ai buckets" on storage.objects
  for delete to authenticated
  using (bucket_id in ('company-logos','blog-images','featured_images'));

drop policy if exists "anon upload company logo" on storage.objects;
create policy "anon upload company logo" on storage.objects
  for insert to anon
  with check (bucket_id = 'company-logos');

-- ============================================================================
-- Seed: blog categories relevant to an AI/ML board
-- ============================================================================
-- Conditional insert: idempotent even if categories.name has no unique constraint yet.
insert into public.categories (name)
select v.name
from (values ('AI Careers'), ('Machine Learning'), ('Data Science'),
             ('Career Guides'), ('Salary & Hiring'), ('Industry News')) as v(name)
where not exists (select 1 from public.categories c where c.name = v.name);
